// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9848uPWU89u-4Zt4gbnK94xAndkcdXUo',
    appId: '1:876525585046:android:1f48222c5daff50ca078b7',
    messagingSenderId: '876525585046',
    projectId: 'chat-app-f0c6f',
    storageBucket: 'chat-app-f0c6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO6WVArEEo4Np9HeNr6BWunS3_5pEU1GQ',
    appId: '1:876525585046:ios:05cc08e522f3b3a3a078b7',
    messagingSenderId: '876525585046',
    projectId: 'chat-app-f0c6f',
    storageBucket: 'chat-app-f0c6f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO6WVArEEo4Np9HeNr6BWunS3_5pEU1GQ',
    appId: '1:876525585046:ios:05cc08e522f3b3a3a078b7',
    messagingSenderId: '876525585046',
    projectId: 'chat-app-f0c6f',
    storageBucket: 'chat-app-f0c6f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7lopf6RN-vWR_VaYzqHltdfFBJ7cangc',
    appId: '1:876525585046:web:fab2f91d760651bca078b7',
    messagingSenderId: '876525585046',
    projectId: 'chat-app-f0c6f',
    authDomain: 'chat-app-f0c6f.firebaseapp.com',
    storageBucket: 'chat-app-f0c6f.firebasestorage.app',
  );
}
